### ISSUE TITLE
Ignore Patterns aren't saved

### ISSUE THREAD

**Issue by adamrabbit** [Zillode/syncthing-silk#11]
I have synced the Download folder as well as some other folders in /storage/emulated/0 - Ignore patterns wont save on any of them. I tried manually editing the .stfolder file but the changes weren't recognised.

**Comment by Zillode** [comment]
Hi @adamrabbit, thanks for your bug report, I will check this.
As a work-around, please add the ignores to `.stignore` instead of `.stfolder` (you might need to create a new file).

**Comment by adamrabbit** [comment]
You're absolutely right! It even says "Editing    /storage/emulated/0/Documents/.stignore" right at the top. My brain must have been in off mode! Thanks :)

**Comment by Zillode** [comment]
It seems the ignore patterns are being saved but we fail to inform the user about this.

**Comment by Zillode** [comment]
Fixed by https://github.com/Zillode/syncthing-silk/commit/8e561d0a7bb9338175c75c24413e9e4377cf46dd
