### ISSUE TITLE
Stops running

### ISSUE THREAD

**Issue by pit001** [Zillode/syncthing-silk#16]
If often stops running. I open it, bring it to the background and its working fine. After some time (maybe after leaving the Wifi range !?) it is not running anymore.

So, I can stay over hours in a friendly wlan (an think al was synced) but nothing happens. :-(

**Comment by Zillode** [comment]
Check your settings, is run on 'wifi' enabled? It is possible that Android tries to safe some battery power by disabling wifi connectivity.

**Comment by pit001** [comment]
Yes, its enabled. And you are right 'Android tries to safe some battery power by disabling wifi connectivity' but after a new wifi connection also ***Silk should be work again.

**Comment by Zillode** [comment]
I think it does this if the app is configured to 'always run'.

**Comment by pit001** [comment]
It's enabled.. 

When to run: Always run
Only on Wifi: checked
Only when connected to: all my trusted wifi's
Only when charging: not checked (a level would be nice - only when battery is more than 30%/50/70%)

**Comment by Zillode** [comment]
ok thanks, will check it out

**Comment by pit001** [comment]
I will keep it observed - tell me if you need a test

**Comment by Zillode** [comment]
https://github.com/OpenSilk/SyncthingAndroid/commit/787bd67920b4869cabbf5d608ff6ff74a2c8dcc0
