### ISSUE TITLE
where to delete folders and devices

### ISSUE THREAD

**Issue by Eddy2909** [Zillode/syncthing-silk#19]

**Comment by Zillode** [comment]
Dup of https://github.com/Zillode/syncthing-silk/issues/13
Open the folder/device, click edit, click delete. If someone else complains about this, I'll add a delete button everywhere:p

**Comment by Eddy2909** [comment]
![screenshot_2015-08-13-11-52-20](https://cloud.githubusercontent.com/assets/12877411/9247265/eadc4d02-41b1-11e5-9045-861deb775eb8.png)
![screenshot_2015-08-13-11-52-27](https://cloud.githubusercontent.com/assets/12877411/9247266/eaf5dfce-41b1-11e5-8e1e-58c72640a6d0.png)

**Comment by Zillode** [comment]
It's in uberprufen' -> delete

**Comment by Eddy2909** [comment]
tnx.. is this app already on transifex? if not - I would translate all strings ;)

**Comment by Eddy2909** [comment]
just tried it - its buggy..
for the default folder I have the following buttons: "Änderungen überschreiben" which could be "override changes" and "überprüfen" which could be scan now
for my manually added folder I do have "überprüfen" and "bearbeiten" (edit)
![screenshot_2015-08-13-20-16-30](https://cloud.githubusercontent.com/assets/12877411/9257854/62e887b6-41f8-11e5-991c-6f4e89169502.png)

If I click on "überprüfen" the button morphes around:
![screenshot_2015-08-13-20-13-19](https://cloud.githubusercontent.com/assets/12877411/9257891/96af7730-41f8-11e5-839f-294ec53e98f0.png)

**Comment by Zillode** [comment]
Thanks, maybe I should enforce english... The buttons seem to be too big in german:)

**Comment by Eddy2909** [comment]
yes :)
but even if its the length, I cant get into the foldersettings of the default folder to delete it :(

**Comment by pit001** [comment]
It's not impossible
en        ->     long GE   ->  shorter GE
Check ->   Überprüfen  -> Prüfen
Change -> bearbeiten -> Ändern
Overwrite Changes -> Änderungen überschreiben -> Ersetzen

(And for the User - not perfect, but use screen rotation )

**Comment by Eddy2909** [comment]
the app could use icons..
