### ISSUE TITLE
Generating secure keys... takes forever

### ISSUE THREAD

**Issue by ghost** [Zillode/syncthing-silk#23]
Generating secure keys... takes forever on my LG G2 Lolli 5.0.1
I can cancel and i get a login screen, i cancel again and syncthing seems to work.
I also cannot shutdown syncthing, it takes also forever. :(

**Comment by Zillode** [comment]
Yeah, I'm improving that code at the moment. If you press back and restart the app it will work I believe.

**Comment by paradoxa** [comment]
Ok, thanks for the info.

**Comment by Zillode** [comment]
Fixed in new version, thanks.
