### ISSUE TITLE
Not available for Samsung Galaxy Tab 7.7?

### ISSUE THREAD

**Issue by UltraStepsi** [Zillode/syncthing-silk#24]
I wonder why I can't download this app from the Play Store for my Samsung Galaxy Tab 7.7 whereas the syncthing-android app ist available. Is there a reason for that? 

Is Android 4.1 too old? I don't see a minimum Android version mentioned in AndroidManfinest.xml...

Btw: Are you going to upload the APK to F-Droid, too?

**Comment by Zillode** [comment]
- Dup of https://github.com/Zillode/syncthing-silk/issues/10
- [Here](https://github.com/Zillode/syncthing-silk/blob/ead21f56c7f93fdac8178c525eab92268229c40a/app/build.gradle#L38)
- Yes

**Comment by UltraStepsi** [comment]
Thank you very much for your very fast and helpful answer. :+1:
