### ISSUE TITLE
Share Folder - "Browse"-Button does not work

### ISSUE THREAD

**Issue by UltraStepsi** [Zillode/syncthing-silk#26]
When I want to choose a disk path I have to use the keyboard and enter it manually as my selection in the file path choosing dialog is not written back into the text field.
The initial value is "/mnt/sdcard" and I can't change it with "BROWSE".

**Comment by Zillode** [comment]
Hmm, works on my phone

**Comment by UltraStepsi** [comment]
Okay, on my Motorola RAZRi with 4.4.2 it works correctly. It doesn't work on my Samsung Galaxy Tab 7.7 with Android 4.0.4 ... But since the ClipboardManager doesn't work their either for whatever strange reason I consider this Samsung Android Update for that device as broken. So Samsung's messed up upadte should not be an issue for you. I will get myself a new tablet instead. --> Resolved
