### ISSUE TITLE
HTC One M8 - Another device cannot be added

### ISSUE THREAD

**Issue by StefanOltmann** [Zillode/syncthing-silk#29]
![screenshot_2015-08-23-18-47-53](https://cloud.githubusercontent.com/assets/9299303/9429412/89390bd2-49cf-11e5-99da-bb79bbe9d5f6.png)

I installed the app out of the Play Store without further configuration, scanned a QR Code and tried to add that device. I found nothing related to that in the logcat.

**Comment by Zillode** [comment]
This is a bug. The Syncthing service was stopped because the app was sent to the background (to scan a barcode).

**Comment by Zillode** [comment]
Fixed in upstream I believe
