### ISSUE TITLE
Don't do retries @ localhost

### ISSUE THREAD

**Issue by UltraStepsi** [Zillode/syncthing-silk#30]
When the local syncthing instance is not running (for whatever reason; maybe crashed) there a several connection tries until the "Cannot reach syncthing; please check your internet connection" warning.
Several reties are indeed useful for remote connections as they may be unrealieable, but if you connect to "localhost" you can directly go to a "syncthing service is not running" message. Or better: Look up if syncthing is running before a connection attempt (and the following timeout).

**Comment by Zillode** [comment]
Dup of https://github.com/Zillode/syncthing-silk/issues/14
