### ISSUE TITLE
no connection to remotes

### ISSUE THREAD

**Issue by Eddy2909** [Zillode/syncthing-silk#32]
hi zillode!
facing some issue:
when adding a remote I got: (first pic with tls, second without)
![screenshot_2015-08-27-10-09-42](https://cloud.githubusercontent.com/assets/12877411/9516058/65209010-4ca6-11e5-849a-6441ee2b968b.png)
![screenshot_2015-08-27-10-14-56](https://cloud.githubusercontent.com/assets/12877411/9516059/652a7224-4ca6-11e5-902a-aa92ae8db136.png)

**Comment by Zillode** [comment]
Fixed in upstream I believe
