### ISSUE TITLE
QR Scanner Support

### ISSUE THREAD

**Issue by senden9** [Zillode/syncthing-silk#39]
A recommendation of Scanners would be nice. This is more helpful as a message like "no compatible scanner found".
I try 2 apps but i seems that no one is supported. One of this was [QR Code Reader](https://play.google.com/store/apps/details?id=me.scan.android.client).

**Comment by Eddy2909** [comment]
I'm always recomending this one:
https://play.google.com/store/apps/details?id=com.google.zxing.client.android
never left me alone :)

**Comment by Zillode** [comment]
Supported in upstream
