### ISSUE TITLE
Controlled external automatic shutdown

### ISSUE THREAD

**Issue by jonada** [Zillode/syncthing-silk#42]
Currently I use the Llama app to start syncthing-silk at night. After a few hours I would like the app to close down automatically, but the force close from LLama does not work and there is no intent to send to syncthing-silk to make it shutdown gracefully.

Would it be possible to add an intent filter to syncthing-silk that responds to requests to shut down the app gracefully?

Instead of using Llama I have experimented with the different "when to run" options, but either I do not understand them or they does not work as intended. Only get to to work reliably with "always run". Is there any documentation describing these options and how they work? I cannot find anything when searching.

Thanks!

**Comment by Eddy2909** [comment]
this is a bug so far.. (https://github.com/Zillode/syncthing-silk/issues/33) after chosing "run when open" in the settings you may shutdown the app.. but be careful: it only runs when display is "awake".. if it should run in the background even if the device is "sleeping", you need to chose "run always"..

**Comment by jonada** [comment]
Thanks for the feedback.

Since there is no information to be found about the different "run options" I have tested them and written about them in issue #33, along with a suggestion to clarify the options.

Now, after finally understandig the options and how they behave I have found a way to handle the particular scenario addressed in this issue. The first one and a haled sentence in the original post describes the need: "Currently I use the Llama app to start syncthing-silk at night. After a few hours I would like to close the app [automatically...]"

Instead of Llama asking Syncthing-Silk to shut down gracefully, one can use the option "between scheduled time". If the app is started (by Llama) within the schedules times it will remain in the background until the end time is reached, at which point the app will shut down gracefully. So Llama can start the app and Scynthing-Silk will shut down gracefully when the end time is reached. Neat!

As long as the option "between scheduled times" remains and keeps working this way this solves the underlying need behind this issue.

**Comment by jonada** [comment]
Rather quickly I noticed that my suggested workaround does not work. It only works when the screen is on, which is quite meaningless.

During night, when the phone is in sleep mode (screen off) and Llama starts Syncthing-silk, nothing happens. In the morning syncthing-silk is running, but has not synced any filea. Its screen is white/blank and nothing happens although it is activated. When leaving the app (just going to home screen) the app closes (because the end time has passed).

So, the scenario to start the app in the background, have it sync, and then gracefully shut down does not work. 

What is your idea on how to solve this need? 

Thanks!

**Comment by Zillode** [comment]
I think you should configure Llama to run the linux arm binary of Syncthing. You can use the `-home` parameter to configure the db and config path and the use webGUI to set up the rest.

Syncthing-Silk already provides a number of features to satisfy controlled sync scenarios, including a schedule, wifi-whitelist and USB charging option. A PR is always welcome though.

**Comment by jonada** [comment]
Thanks for the info. Currently I do not have enough knowledge to accomplish that. Seems I'll have to learn the technical details one day.

**Comment by jonada** [comment]
You state: "Syncthing-Silk already provides a number of features to satisfy controlled sync scenarios, including a schedule". In issue #33, I clarify how the scheduling option behaves:

"This is the most confusing option. If you manually start the app it stays on in the background until the end time is reached, then it gracefully closes down. However, it does not automatically start when the start time is reached (which would be the expected option). You have to manually start the app to make it run again. When manually started, the app gracefully shuts down when you leave the app and the current time is not within the schedule."

So, the scheduling feature is quite limited. You have to start the app manually every day within the scheduled times to have the schedule work. That's not much of a schedule. If it only worked starting the app automatically (e.g., with Llama), then it would be fine. But it doesn't work. 

Please explain in what way the schedling functionality as it currently behaves is a feature. Thanks!

**Comment by Zillode** [comment]
There was a bug related to the schedule feature that caused it not to start. This is fixed in the f-droid version. Simply add https://ssl.opensilk.org/fdroid/repo to the repositories of the F-Droid app and install Syncthing-Silk
