### ISSUE TITLE
Update Silk for 0.12

### ISSUE THREAD

**Issue by edrex** [Zillode/syncthing-silk#46]
I'm running my own build of Silk, since I never got the stock Android app to work properly.

@Zillode what do you think is needed to get Silk ready for 0.12?

## :fire: Critical

- [x] Update Syncthing to 0.12
- [x] Add relay server config to settings
- [x] Folder Path field doesn't update with browse [#45](https://github.com/Zillode/syncthing-silk/issues/45)

## :iphone: UI Parity:

 - [x] Pause device
 - ? Folder scanning progress indicator

Does anything need to be done WRT [release signing](http://docs.syncthing.net/dev/release-signing.html), or does the binary always update with the app?

**Comment by Zillode** [comment]
- See https://github.com/Zillode/syncthing-silk/milestones/Next for things to be resolved for a next 'proper' release.

- Updating to 0.12 is not too hard, there are only two changes necessary in `api/model` during my initial tests.

- To support relays we have to resolve the ip addresses manually (see https://github.com/Zillode/syncthing-silk/issues/4 and https://github.com/syncthing/syncthing-android/commit/2928091e23a642f583d5d91c4f15592c1f4a2247 for inspiration)

- No, this repo uses git submodules (https://github.com/Zillode/syncthing-silk/tree/master/syncthing/src/github.com/syncthing) and the apk can be built on the official servers (http://android.syncthing.net)

**Comment by drewis** [comment]
Ive addressed most of these upstream
https://github.com/OpenSilk/SyncthingAndroid/commit/66e74f29bc75dc0c21a033bad16af9735504600e
https://github.com/OpenSilk/SyncthingAndroid/commit/9acf6cc81ce6202871489152a0706311587f828b
https://github.com/OpenSilk/SyncthingAndroid/commit/8f537c42e039319ab24d486b68bde803f16da7b2
https://github.com/OpenSilk/SyncthingAndroid/commit/a7bf096e0c0d3b55f73caacbf6c1e7a5dfe5f8b9

**Comment by Zillode** [comment]
Cool, I'll rebase from upstream
