### ISSUE TITLE
Never finishes generating keys

### ISSUE THREAD

**Issue by nebbishhacker** [Zillode/syncthing-silk#5]
I installed syncthing-silk off the play store on my galaxy nexus, and it just sits spinning on the "Generating Secure Keys" screen forever, even when I leave it for a couple hours.

**Comment by Zillode** [comment]
@nebbishhacker is the syncthing-android app installed as well?

**Comment by nebbishhacker** [comment]
It was, but then I uninstalled it and reinstalled the syncthing-silk app with the same results

**Comment by Zillode** [comment]
I'll try to reproduce this by installing syncthing-android. I think if you trully uninstall syncthing-silk again, it should work. If not, please capture a [logcat](http://forum.xda-developers.com/showthread.php?t=1726238).

**Comment by nebbishhacker** [comment]
I unistalled and reinstalled syncthing-silk again, and let it run for an hour. Same thing. Here's the log: https://www.dropbox.com/s/7khu0vsumac3y2n/2015-08-03-18-54-48.txt?dl=0

**Comment by Zillode** [comment]
```
08-03 18:55:34.791 D/ServiceSettings( 5931): isAllowedToRun(): nope!
```

**Comment by Zillode** [comment]
Fixed by https://github.com/Zillode/syncthing-silk/commit/6affdbc32ef16bb4c3ba3cf36abdeadb0b73e4d8#diff-ae9256c8a0c2da0187b21cd8dc72dfa0R102
